# Site settings

title: Project Pages
header-img: img/Active_header.jpg
email: perrywmellis@users.noreply.github.com
description: "Characterizing Active Nematics on the Surface of a Torus"
baseurl: "/MIC-Active-Nematics-Torus"
url: "http://Materials-Informatics-Class-Fall2015.github.io"
github_username:  perrywmellis
project_repository: MIC-Active-Nematics-Torus
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
